apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    name: test1
spec:
  containers:
  - name: test
    image: nginx:alpine
    resources:
      limits:
        memory: "32Mi"
        cpu: "50m"
    ports:
      - containerPort: 80
