apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
spec:
  replicas: 10
  selector:
  ## Identify which PODS should be part of this Set
    matchLabels:
      name: myapp
  template: # Begining of POD Template
    metadata:
    ## define name of POD (Must MATCH with Line# 10 )
      name: myapp
      labels:
        name: myapp
    spec:
      containers:
        - image: mahendrshinde/myweb:latest
          name: web
          ports:
            - containerPort: 80